import { Doctor } from './types';

export const DOCTORS_DATA: Doctor[] = [
  {
    id: 'doc-1',
    name: 'dr. Luty Diah Prahmani, Sp.A',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Anak',
    experience: 11,
    rating: 4.91,
    image: '/assets/images/dokter/SPAN/RSYASMIN_SPA01-dr. Luty Diah Prahmani. SpA.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Anak',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 12:00' },
    bio: 'Kami memahami setiap kekhawatiran orang tua saat buah hati sedang sakit. Dengan pelayanan Spesialis Anak yang hangat, pemeriksaan menyeluruh, pemantauan tumbuh kembang, imunisasi, serta penanganan berbagai masalah kesehatan anak, kami mendampingi setiap langkah perawatan agar si kecil dapat tumbuh sehat, aktif, dan ceria.',
    education: 'Dokter Spesialis Anak',
    color: '#0d9488'
  },
  {
    id: 'doc-2',
    name: 'dr. Muhammad Irvan Avandi, Sp.A',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Anak',
    experience: 8,
    rating: 4.88,
    image: '/assets/images/dokter/SPAN/RSYASMIN_SPA02-dr. Muhammad Irvan Avandi. SpA.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Anak',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '09:00 - 13:00' },
    bio: 'Kami percaya setiap anak berhak mendapatkan pelayanan kesehatan terbaik. Dengan pendekatan berbasis ilmu kedokteran terkini, kami memberikan konsultasi, diagnosis, pengobatan, serta edukasi kepada orang tua agar tumbuh kembang anak berlangsung optimal dengan rasa aman dan penuh kepercayaan.',
    education: 'Dokter Spesialis Anak',
    color: '#0d9488'
  },
  {
    id: 'doc-3',
    name: 'dr. Naufal Sastra Negara, Sp.A',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Anak',
    experience: 7,
    rating: 4.85,
    image: '/assets/images/dokter/SPAN/RSYASMIN_SPA03-dr. Naufal Sastra Negara. SpA.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Anak',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'], hours: '08:00 - 11:30' },
    bio: 'Kami memahami bahwa melihat anak sakit adalah pengalaman yang tidak mudah bagi setiap orang tua. Melalui pelayanan yang profesional, komunikatif, dan penuh empati, kami memberikan pemeriksaan, diagnosis, serta terapi yang tepat agar anak merasa nyaman dan memperoleh penanganan yang sesuai kebutuhannya.',
    education: 'Dokter Spesialis Anak',
    color: '#0d9488'
  },
  {
    id: 'doc-4',
    name: 'dr. Danang Dwi Atmojo, Sp.An',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Anestesi',
    experience: 10,
    rating: 4.87,
    image: '/assets/images/dokter/SPAN/RSYASMIN_SPAN01-dr. Danang Dwi Atmojo. Sp.An.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Anestesi',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '13:00 - 16:00' },
    bio: 'Kami memahami bahwa menjelang tindakan operasi sering kali menimbulkan rasa cemas. Dengan pelayanan anestesi yang modern, pemantauan ketat sebelum, selama, dan setelah tindakan, serta pengelolaan nyeri yang optimal, kami berkomitmen menjaga keselamatan dan kenyamanan pasien selama proses perawatan.',
    education: 'Dokter Spesialis Anestesi',
    color: '#b45309'
  },
  {
    id: 'doc-5',
    name: 'dr. Ovi Octavia Karamoy, Sp.An',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Anestesi',
    experience: 9,
    rating: 4.89,
    image: '/assets/images/dokter/SPAN/RSYASMIN_SPAN02-dr. Ovi Octavia Karamoy. Sp.An v1.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Anestesi',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '14:00 - 18:00' },
    bio: 'Kami hadir untuk membantu setiap pasien menjalani tindakan operasi dengan lebih tenang. Melalui pelayanan anestesi yang profesional, pemantauan intensif, serta pengelolaan nyeri yang sesuai kebutuhan, kami mendukung keberhasilan tindakan medis dengan mengutamakan keselamatan dan kenyamanan pasien.',
    education: 'Dokter Spesialis Anestesi',
    color: '#b45309'
  },
  {
    id: 'doc-6',
    name: 'Dr. dr. Chairul Yahya, Sp.OT',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Bedah Tulang',
    experience: 16,
    rating: 4.95,
    image: '/assets/images/dokter/SPOT/RSYASMIN_SPAN01-Dr. dr. Chairul Yahya. Sp.OT.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Orthopedi dan Traumatologi',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '10:00 - 15:00' },
    bio: 'Kami memahami bahwa gangguan tulang, sendi, maupun cedera dapat membatasi aktivitas dan kualitas hidup. Dengan pelayanan ortopedi yang komprehensif, kami membantu mendiagnosis, menangani, serta mendampingi proses pemulihan agar pasien dapat kembali bergerak aktif dan menjalani aktivitas dengan lebih nyaman.',
    education: 'Dokter Spesialis Orthopedi',
    color: '#be123c'
  },
  {
    id: 'doc-7',
    name: 'dr. Reza Muttaqien, Sp.OT',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Bedah Tulang',
    experience: 8,
    rating: 4.91,
    image: '/assets/images/dokter/SPOT/RSYASMIN_SPAN02-dr. Reza Muttaqien. Sp. OT.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Orthopedi dan Traumatologi',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis'], hours: '16:00 - 19:30' },
    bio: 'Kami percaya setiap pasien berhak kembali menikmati aktivitas tanpa rasa nyeri. Melalui pelayanan ortopedi yang profesional, mulai dari konsultasi, diagnosis, hingga penanganan gangguan tulang, sendi, dan cedera, kami membantu memulihkan fungsi gerak serta meningkatkan kualitas hidup pasien.',
    education: 'Dokter Spesialis Orthopedi',
    color: '#be123c'
  },
  {
    id: 'doc-8',
    name: 'dr. Erwin Kurniawan, Sp.B., M.Ked.Klin',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Bedah Umum',
    experience: 9,
    rating: 4.86,
    image: '/assets/images/dokter/SPBU/RSYASMIN_SPBU01-dr. Erwin Kurniawan, Sp.B. M.Ked.Klin.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Bedah Umum',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 12:00' },
    bio: 'Kami memahami bahwa keputusan menjalani operasi bukanlah hal yang mudah. Dengan pelayanan bedah yang menyeluruh, mulai dari konsultasi, tindakan operasi, hingga perawatan pascaoperasi, kami berkomitmen memberikan penanganan yang aman, profesional, dan berorientasi pada pemulihan terbaik bagi setiap pasien.',
    education: 'Dokter Spesialis Bedah',
    color: '#0369a1'
  },
  {
    id: 'doc-9',
    name: 'dr. Norman Christy Ramadhyas, Sp.B',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Bedah Umum',
    experience: 7,
    rating: 4.82,
    image: '/assets/images/dokter/SPBU/RSYASMIN_SPBU02-dr. Norman Christy Ramadhyas. Sp.B.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Bedah Umum',
    schedule: { days: ['Rabu', 'Kamis', 'Jumat'], hours: '10:00 - 14:00' },
    bio: 'Kami mendampingi setiap pasien yang membutuhkan tindakan bedah dengan pelayanan yang profesional dan penuh perhatian. Melalui diagnosis yang tepat, tindakan operasi yang sesuai indikasi, serta pemantauan selama masa pemulihan, kami berupaya memberikan hasil perawatan yang optimal dengan tetap mengutamakan keselamatan pasien.',
    education: 'Dokter Spesialis Bedah',
    color: '#0369a1'
  },
  {
    id: 'doc-10',
    name: 'dr. Radhi Bakarman, Sp.B., FICS',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Bedah Umum',
    experience: 11,
    rating: 4.96,
    image: '/assets/images/dokter/SPBU/RSYASMIN_SPBU03-dr. Radhi Bakarman. Sp.B, FICS.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Bedah Umum',
    schedule: { days: ['Selasa', 'Rabu', 'Kamis'], hours: '11:00 - 15:30' },
    bio: 'Kami menghadirkan pelayanan bedah yang mengutamakan standar keselamatan, ketepatan tindakan, dan kenyamanan pasien. Didukung kompetensi bedah yang luas serta pengalaman profesional, kami memberikan pelayanan komprehensif mulai dari konsultasi hingga perawatan pascaoperasi untuk membantu proses pemulihan secara optimal.',
    education: 'Dokter Spesialis Bedah',
    color: '#0369a1'
  },
  {
    id: 'doc-12',
    name: 'drg. Rianita Romadhoni, Sp.KGA',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Gigi Anak',
    experience: 8,
    rating: 4.77,
    image: '/assets/images/dokter/SPGA/RSYASMIN_SPGA01-drg. Rianita Romadhoni. Sp.KGA.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Kedokteran Gigi Anak',
    schedule: { days: ['Rabu', 'Sabtu'], hours: '08:30 - 12:30' },
    bio: 'Kami ingin setiap anak merasa nyaman saat berkunjung ke dokter gigi. Dengan pendekatan yang ramah anak, kami memberikan pelayanan kesehatan gigi dan mulut mulai dari pemeriksaan, perawatan, hingga edukasi, sehingga pengalaman ke dokter gigi menjadi lebih menyenangkan sekaligus mendukung tumbuh kembang anak yang optimal.',
    education: 'Dokter Gigi Spesialis Anak',
    color: '#db2777'
  },
  {
    id: 'doc-13',
    name: 'drg. Hendrijaya Permana, Sp.BMM',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Bedah Mulut',
    experience: 9,
    rating: 4.85,
    image: '/assets/images/dokter/SPBGM/RSYASMIN_SPBGM01-drg. Hendrijaya Permana, Sp.BMM.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Bedah Mulut',
    schedule: { days: ['Senin', 'Kamis'], hours: '08:00 - 11:30' },
    bio: 'Kami memahami bahwa tindakan bedah mulut sering menimbulkan rasa khawatir. Dengan ketepatan diagnosis, tindakan yang sesuai standar, serta mengutamakan keselamatan pasien, kami memberikan pelayanan bedah mulut dan maksilofasial untuk membantu mengembalikan fungsi, kesehatan, dan kepercayaan diri pasien.',
    education: 'Dokter Gigi Spesialis Bedah Mulut',
    color: '#db2777'
  },
  {
    id: 'doc-14',
    name: 'drg. Iyanda Vemala, Sp.Ort',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Ortodontis',
    experience: 7,
    rating: 4.82,
    image: '/assets/images/dokter/SPGO/RSYASMIN_SPGO01-drg. Iyanda Vemala., Sp.Ort.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Ortodonti',
    schedule: { days: ['Rabu', 'Sabtu'], hours: '13:00 - 16:00' },
    bio: 'Kami percaya senyum yang rapi dapat meningkatkan rasa percaya diri dan kualitas hidup. Melalui pelayanan ortodonti yang menyeluruh, kami membantu memperbaiki susunan gigi dan hubungan rahang dengan perencanaan perawatan yang tepat sesuai kebutuhan setiap pasien.',
    education: 'Dokter Gigi Spesialis Ortodonti',
    color: '#db2777'
  },
  {
    id: 'doc-15',
    name: 'drg. Shiffin Devi Mardiyana, Sp.PM',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Penyakit Mulut',
    experience: 6,
    rating: 4.79,
    image: '/assets/images/dokter/SPPGM/RSYASMIN_SPPGM01-drg. Shiffin Devi Mardiyana, Sp.PM.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Penyakit Mulut',
    schedule: { days: ['Selasa', 'Kamis', 'Jumat'], hours: '15:00 - 18:30' },
    bio: 'Kami memahami bahwa kesehatan gusi merupakan fondasi dari kesehatan gigi yang baik. Dengan pelayanan periodonsia yang komprehensif, kami membantu mencegah, mendiagnosis, dan menangani berbagai penyakit gusi serta jaringan penyangga gigi agar kesehatan rongga mulut tetap terjaga dalam jangka panjang.',
    education: 'Dokter Gigi Spesialis Penyakit Mulut',
    color: '#db2777'
  },
  {
    id: 'doc-16',
    name: 'drg. Wildhan Septianda Bhakti, Sp.Perio',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Periodonsia',
    experience: 8,
    rating: 4.91,
    image: '/assets/images/dokter/SPPGP/RSYASMIN_SPPGP01-drg. Wildhan Septianda Bhakti., Sp.Perio.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Periodonsia',
    schedule: { days: ['Senin', 'Rabu', 'Kamis'], hours: '09:00 - 13:00' },
    bio: 'Kami membantu menjaga kesehatan gusi dan jaringan pendukung gigi agar senyum tetap sehat dan nyaman. Melalui diagnosis yang tepat serta terapi periodonsia yang komprehensif, kami mendampingi pasien dalam mempertahankan kesehatan gigi untuk jangka panjang.',
    education: 'Dokter Gigi Spesialis Periodonsia',
    color: '#db2777'
  },
  {
    id: 'doc-17',
    name: 'drg. Ali Surahman Fatahillah, Sp.Pros',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Prostodonsia',
    experience: 8,
    rating: 4.88,
    image: '/assets/images/dokter/SPGP/RSYASMIN_SPGP01-drg. Ali Surahman Fatahillah, Sp.Pros.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Prostodonsia',
    schedule: { days: ['Selasa', 'Jumat'], hours: '08:00 - 11:30' },
    bio: 'Kami memahami bahwa kehilangan atau kerusakan gigi dapat memengaruhi fungsi mengunyah maupun rasa percaya diri. Dengan pelayanan prostodonsia yang profesional, kami menghadirkan solusi restorasi seperti gigi tiruan, mahkota, dan jembatan gigi untuk membantu mengembalikan fungsi serta estetika senyum pasien.',
    education: 'Dokter Gigi Spesialis Prostodonsia',
    color: '#db2777'
  },
  {
    id: 'doc-18',
    name: 'drg. Bimbi Virgamantya',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Gigi Umum',
    experience: 7,
    rating: 4.93,
    image: '/assets/images/dokter/SPGU/RSYASMIN_SPGU01-drg. Bimbi Virgamantya - Copy.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Gigi Umum',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'], hours: '07:30 - 14:00' },
    bio: 'Kami memberikan pelayanan kesehatan gigi dan mulut untuk seluruh anggota keluarga dengan mengutamakan kenyamanan, komunikasi yang baik, serta tindakan yang sesuai kebutuhan pasien. Kami percaya senyum yang sehat berawal dari perawatan yang rutin dan menyenangkan.',
    education: 'Dokter Gigi Umum',
    color: '#db2777'
  },
  {
    id: 'doc-19',
    name: 'drg. Ilyas E.R',
    specialty: 'Gigi & Mulut',
    subSpecialty: 'Gigi Umum',
    experience: 9,
    rating: 4.86,
    image: '/assets/images/dokter/SPGU/RSYASMIN_SPGU02-drg. Ilyas E.R.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Gigi Umum',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 12:00' },
    bio: 'Kami memahami bahwa keluhan gigi dapat mengganggu aktivitas sehari-hari. Melalui pemeriksaan menyeluruh, penambalan, pencabutan, pembersihan karang gigi, serta edukasi kesehatan gigi dan mulut, kami membantu menjaga kenyamanan dan kesehatan senyum Anda.',
    education: 'Dokter Gigi Umum',
    color: '#db2777'
  },
  {
    id: 'doc-20',
    name: 'dr. Nelly Mulyaningsih, Sp.JP(K), FIHA, FAsCC',
    specialty: 'Spesialis Medis',
    subSpecialty: 'Jantung',
    experience: 11,
    rating: 4.9,
    image: '/assets/images/dokter/SPJPB/RSYASMIN_SPJPB01-dr. Nelly Mulyaningsih, Sp.JP-K, FIHA, FAsCC.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Jantung dan Pembuluh Darah',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '13:00 - 17:00' },
    bio: 'Kami memahami bahwa kesehatan jantung merupakan bagian penting dari kualitas hidup. Dengan pelayanan konsultasi, deteksi dini, diagnosis, pengobatan, dan pemantauan penyakit jantung serta pembuluh darah yang didukung kompetensi konsultan, kami berkomitmen memberikan penanganan yang profesional, menyeluruh, dan berorientasi pada keselamatan pasien.',
    education: 'Dokter Spesialis Jantung',
    color: '#ca8a04'
  },
  {
    id: 'doc-21',
    name: 'dr. Rizki Amalia, Sp.JP',
    specialty: 'Spesialis Medis',
    subSpecialty: 'Jantung',
    experience: 8,
    rating: 4.94,
    image: '/assets/images/dokter/SPJPB/RSYASMIN_SPJPB02-dr. Rizki Amalia, Sp.JP..png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Jantung dan Pembuluh Darah',
    schedule: { days: ['Senin', 'Kamis'], hours: '14:00 - 17:30' },
    bio: 'Kami percaya kesehatan jantung yang terjaga adalah kunci untuk menjalani hidup yang lebih berkualitas. Melalui pelayanan konsultasi, deteksi dini, diagnosis, pengobatan, dan pemantauan penyakit jantung serta pembuluh darah, kami mendampingi setiap pasien dengan pendekatan yang komprehensif, profesional, dan penuh perhatian.',
    education: 'Dokter Spesialis Jantung',
    color: '#ca8a04'
  },
  {
    id: 'doc-22',
    name: 'dr. Haris Wibawanto, Sp.OG',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Kandungan',
    experience: 11,
    rating: 4.87,
    image: '/assets/images/dokter/SPKB/RSYASMIN_SPKB01-dr. Haris Wibawanto, SpOG.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Obstetri dan Ginekologi',
    schedule: { days: ['Rabu', 'Jumat'], hours: '15:00 - 19:00' },
    bio: 'Kami memahami bahwa setiap perjalanan menjadi seorang ibu adalah pengalaman yang berharga. Melalui pelayanan kehamilan, persalinan, kesehatan reproduksi wanita, serta program kehamilan, kami mendampingi setiap tahap dengan pemeriksaan yang menyeluruh, pelayanan yang profesional, dan perhatian terhadap kesehatan ibu maupun buah hati.',
    education: 'Dokter Spesialis Kandungan',
    color: '#0d9488'
  },
  {
    id: 'doc-23',
    name: 'dr. M. Nasir, Sp.OG(K) FM',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Kandungan',
    experience: 11,
    rating: 4.8,
    image: '/assets/images/dokter/SPKB/RSYASMIN_SPKB02-dr. M. Nasir SpOG-K FM.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Obstetri dan Ginekologi',
    schedule: { days: ['Selasa', 'Sabtu'], hours: '09:00 - 12:00' },
    bio: 'Kami memahami bahwa kehamilan risiko tinggi membutuhkan perhatian dan pemantauan yang lebih intensif. Dengan pelayanan fetomaternal yang komprehensif, kami mendampingi ibu dan janin melalui pemantauan yang cermat, konsultasi yang menyeluruh, serta penanganan sesuai kondisi medis untuk mendukung kehamilan yang lebih aman.',
    education: 'Dokter Spesialis Kandungan',
    color: '#0d9488'
  },
  {
    id: 'doc-24',
    name: 'dr. Zaenal Arifin, Sp.OG',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Kandungan',
    experience: 9,
    rating: 4.82,
    image: '/assets/images/dokter/SPKB/RSYASMIN_SPKB03-dr. Zaenal Arifin, SpOG.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Obstetri dan Ginekologi',
    schedule: { days: ['Senin', 'Kamis'], hours: '13:00 - 16:30' },
    bio: 'Kami berkomitmen mendampingi kesehatan wanita di setiap fase kehidupan. Melalui pelayanan pemeriksaan kehamilan, persalinan, kesehatan reproduksi, hingga penanganan berbagai gangguan kandungan, kami memberikan pelayanan yang profesional, nyaman, dan menghargai privasi setiap pasien.',
    education: 'Dokter Spesialis Kandungan',
    color: '#0d9488'
  },
  {
    id: 'doc-25',
    name: 'Dra. Nining Naimah Jaidi, MCH, M.Psi., Psikolog',
    specialty: 'Kesehatan Mental',
    subSpecialty: 'Konselor',
    experience: 5,
    rating: 4.89,
    image: '/assets/images/dokter/SPKON/RSYASMIN_SPKON01-Dra. Nining Naimah Jaidi, MCH, M.Psi, Kons..png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Psikolog Klinis',
    schedule: { days: ['Rabu', 'Jumat'], hours: '10:00 - 13:00' },
    bio: 'Kami memahami bahwa setiap orang dapat menghadapi tantangan emosional dalam kehidupannya. Melalui layanan konsultasi, asesmen psikologis, dan pendampingan yang empatik, kami membantu Anda menemukan cara yang lebih sehat dalam menghadapi berbagai permasalahan serta meningkatkan kualitas hidup.',
    education: 'Magister Psikologi',
    color: '#0891b2'
  },
  {
    id: 'doc-26',
    name: 'dr. Gede Arna A., Sp.KK',
    specialty: 'Spesialis Medis',
    subSpecialty: 'Kulit & Kelamin',
    experience: 10,
    rating: 4.87,
    image: '/assets/images/dokter/SPKK/RSYASMIN_SPKK01-dr. Gede Arna A, SpKK.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Kulit dan Kelamin',
    schedule: { days: ['Senin', 'Kamis'], hours: '08:00 - 12:00' },
    bio: 'Kami memahami bahwa kesehatan kulit tidak hanya memengaruhi penampilan, tetapi juga kenyamanan dan rasa percaya diri. Dengan pelayanan diagnosis dan penanganan berbagai penyakit kulit, rambut, kuku, serta infeksi menular seksual, kami memberikan perawatan yang profesional sesuai kebutuhan setiap pasien.',
    education: 'Dokter Spesialis Kulit dan Kelamin',
    color: '#ca8a04'
  },
  {
    id: 'doc-27',
    name: 'dr. Dina Wahyu Wibawati, Sp.M',
    specialty: 'Spesialis Medis',
    subSpecialty: 'Mata',
    experience: 11,
    rating: 4.91,
    image: '/assets/images/dokter/SPMT/RSYASMIN_SPMT01-dr. Dina Wahyu Wibawati, SpM.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Mata',
    schedule: { days: ['Selasa', 'Jumat'], hours: '09:00 - 13:00' },
    bio: 'Kami percaya penglihatan yang baik adalah bagian penting dari kualitas hidup. Melalui pemeriksaan mata yang menyeluruh, diagnosis yang tepat, serta penanganan berbagai gangguan penglihatan dan penyakit mata, kami membantu menjaga kesehatan mata agar Anda dapat menikmati setiap momen dengan lebih jelas.',
    education: 'Dokter Spesialis Mata',
    color: '#ca8a04'
  },
  {
    id: 'doc-28',
    name: 'dr. Elok Hikmatun Nikmah, Sp.P',
    specialty: 'Spesialis Medis',
    subSpecialty: 'Paru',
    experience: 9,
    rating: 4.9,
    image: '/assets/images/dokter/SPPR/RSYASMIN_SPPR01-dr. Elok Hikmatun Nikmah, Sp.P.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Paru',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'], hours: '24 Jam (On-Call)' },
    bio: 'Kami memahami bahwa gangguan pernapasan dapat menghambat aktivitas sehari-hari. Dengan pelayanan konsultasi, diagnosis, pengobatan, dan pemantauan berbagai penyakit paru, kami membantu pasien memperoleh penanganan yang tepat agar dapat bernapas lebih nyaman dan menjalani aktivitas dengan lebih baik.',
    education: 'Dokter Spesialis Paru',
    color: '#ca8a04'
  },
  {
    id: 'doc-29',
    name: 'dr. Ririek Parwitasari, Sp.P',
    specialty: 'Spesialis Medis',
    subSpecialty: 'Paru',
    experience: 8,
    rating: 4.88,
    image: '/assets/images/dokter/SPPR/RSYASMIN_SPPR02-dr. Ririek Parwitasari, SpP.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Paru',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'], hours: '08:00 - 15:00' },
    bio: 'Kami hadir untuk membantu menjaga kesehatan paru dan sistem pernapasan melalui pelayanan konsultasi, diagnosis, pengobatan, serta edukasi kesehatan. Dengan pendekatan yang menyeluruh, kami mendampingi pasien dalam mengatasi berbagai gangguan paru agar kualitas hidup tetap terjaga.',
    education: 'Dokter Spesialis Paru',
    color: '#ca8a04'
  },
  {
    id: 'doc-30',
    name: 'dr. Aditya Ignasius Sigit, Sp.PK',
    specialty: 'Penunjang Diagnostik',
    subSpecialty: 'Patologi Klinis',
    experience: 10,
    rating: 4.86,
    image: '/assets/images/dokter/SPPK/RSYASMIN_SPPK01-dr. Aditya Ignasius Sigit, SpPK.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Patologi Klinis',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 14:00' },
    bio: 'Kami mendukung ketepatan diagnosis melalui interpretasi pemeriksaan laboratorium klinik yang akurat dan terpercaya. Dengan pelayanan Patologi Klinik yang profesional, kami membantu dokter penanggung jawab menentukan diagnosis dan rencana terapi yang tepat sehingga pasien memperoleh penanganan yang optimal.',
    education: 'Dokter Spesialis Patologi Klinis',
    color: '#475569'
  },
  {
    id: 'doc-31',
    name: 'dr. Herry S., Sp.PD, FINASIM',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Penyakit Dalam',
    experience: 11,
    rating: 4.92,
    image: '/assets/images/dokter/SPPD/RSYASMIN_SPPD01-dr. Herry S, Sp.PD. FINASIM.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Penyakit Dalam',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '09:00 - 13:00' },
    bio: 'Kami memahami bahwa kesehatan yang baik berawal dari penanganan yang tepat. Melalui pelayanan Spesialis Penyakit Dalam yang komprehensif, kami memberikan konsultasi, diagnosis, pengobatan, serta pemantauan berbagai penyakit pada orang dewasa dengan mengutamakan keselamatan, kenyamanan, dan kualitas hidup pasien.',
    education: 'Dokter Spesialis Penyakit Dalam',
    color: '#4f46e5'
  },
  {
    id: 'doc-32',
    name: 'dr. Kurnia Alisaputri, Sp.PD',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Penyakit Dalam',
    experience: 11,
    rating: 4.88,
    image: '/assets/images/dokter/SPPD/RSYASMIN_SPPD02-dr. Kurnia Alisaputri, Sp.PD.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Penyakit Dalam',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 12:00 & 13:00 - 16:00' },
    bio: 'Kami percaya bahwa deteksi dini dan penanganan yang tepat dapat membantu menjaga kesehatan jangka panjang. Dengan pelayanan Spesialis Penyakit Dalam yang menyeluruh, kami memberikan konsultasi, diagnosis, terapi, serta edukasi kesehatan sesuai kebutuhan setiap pasien agar tetap aktif and produktif.',
    education: 'Dokter Spesialis Penyakit Dalam',
    color: '#4f46e5'
  },
  {
    id: 'doc-33',
    name: 'dr. Mahresya Kamajaya, Sp.PD',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Penyakit Dalam',
    experience: 8,
    rating: 4.85,
    image: '/assets/images/dokter/SPPD/RSYASMIN_SPPD03-dr. Mahresya Kamajaya, Sp.PD.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Penyakit Dalam',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '14:00 - 18:00' },
    bio: 'Kami memahami bahwa setiap keluhan kesehatan memiliki cerita yang berbeda. Melalui konsultasi yang menyeluruh, diagnosis yang akurat, serta terapi yang sesuai, kami mendampingi pasien dalam setiap tahap perawatan dengan komunikasi yang baik dan pelayanan yang profesional.',
    education: 'Dokter Spesialis Penyakit Dalam',
    color: '#4f46e5'
  },
  {
    id: 'doc-34',
    name: 'dr. Median Brahmantyo, Sp.PD',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Penyakit Dalam',
    experience: 7,
    rating: 4.87,
    image: '/assets/images/dokter/SPPD/RSYASMIN_SPPD04-dr. Median Brahmantyo, Sp.PD.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Penyakit Dalam',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'], hours: '08:00 - 14:00' },
    bio: 'Kami berkomitmen memberikan pelayanan Penyakit Dalam yang komprehensif untuk berbagai penyakit akut maupun kronis. Dengan pemantauan yang berkesinambungan, diagnosis yang tepat, serta terapi yang sesuai, kami membantu pasien menjaga kesehatan dan meningkatkan kualitas hidup.',
    education: 'Dokter Spesialis Penyakit Dalam',
    color: '#4f46e5'
  },
  {
    id: 'doc-35',
    name: 'Betty Kumala Febriawati, S.Psi., M.Psi., Psikolog',
    specialty: 'Kesehatan Mental',
    subSpecialty: 'Psikolog',
    experience: 5,
    rating: 4.89,
    image: '/assets/images/dokter/SPPS/RSYASMIN_SPPS01-Betty Kumala Febriawati, S.Psi.,M.Psi., Psikolog.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Psikolog Klinis',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 12:00' },
    bio: 'Kami memahami bahwa kesehatan mental merupakan bagian penting dari kesejahteraan hidup. Melalui layanan konsultasi, asesmen psikologis, dan pendampingan yang empatik, kami membantu anak, remaja, dewasa, maupun keluarga menghadapi berbagai tantangan hidup dengan lebih percaya diri.',
    education: 'Sarjana Psikologi, Magister Psikologi',
    color: '#0891b2'
  },
  {
    id: 'doc-36',
    name: 'Cinta Retsa Ferdiana, S.Psi., M.Psi., Psikolog',
    specialty: 'Kesehatan Mental',
    subSpecialty: 'Psikolog',
    experience: 5,
    rating: 4.91,
    image: '/assets/images/dokter/SPPS/RSYASMIN_SPPS02-Cinta Retsa Ferdiana, S.Psi., M.Psi.,Psikolog.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Psikolog Klinis',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '09:00 - 13:00' },
    bio: 'Kami percaya setiap individu memiliki potensi untuk bangkit dan berkembang. Dengan layanan konsultasi psikologis yang profesional, suasana yang nyaman, dan pendekatan tanpa menghakimi, kami mendampingi Anda menemukan solusi terbaik untuk menghadapi berbagai tantangan emosional maupun pengembangan diri.',
    education: 'Sarjana Psikologi, Magister Psikologi',
    color: '#0891b2'
  },
  {
    id: 'doc-37',
    name: 'dr. Mochammad Nizam Fahmi, Sp.Rad.(K) RI',
    specialty: 'Penunjang Diagnostik',
    subSpecialty: 'Radiologi',
    experience: 10,
    rating: 4.93,
    image: '/assets/images/dokter/SPRAD/RSYASMIN_SPRAD01-dr. Mochammad Nizam Fahmi, Sp.Rad.(K) RI.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Radiologi',
    schedule: { days: ['Rabu', 'Sabtu'], hours: '08:30 - 12:30' },
    bio: 'Kami mendukung pelayanan medis melalui interpretasi pemeriksaan radiologi yang akurat dan komprehensif. Dengan keahlian di bidang radiologi, kami membantu dokter penanggung jawab memperoleh informasi yang tepat sebagai dasar dalam menentukan diagnosis dan rencana penanganan pasien.',
    education: 'Dokter Spesialis Radiologi',
    color: '#475569'
  },
  {
    id: 'doc-38',
    name: 'dr. Yori Primanda, Sp.Rad.',
    specialty: 'Penunjang Diagnostik',
    subSpecialty: 'Radiologi',
    experience: 8,
    rating: 4.84,
    image: '/assets/images/dokter/SPRAD/RSYASMIN_SPRAD02-dr. Yori Primanda, Sp.Rad..png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Radiologi',
    schedule: { days: ['Senin', 'Kamis'], hours: '08:00 - 11:30' },
    bio: 'Kami menghadirkan pelayanan radiologi yang akurat untuk membantu proses diagnosis berbagai kondisi medis. Melalui pemeriksaan pencitraan yang tepat dan interpretasi profesional, kami mendukung dokter dalam menentukan penanganan terbaik bagi setiap pasien.',
    education: 'Dokter Spesialis Radiologi',
    color: '#475569'
  },
  {
    id: 'doc-39',
    name: 'dr. Juwita Raudlatul Salsabil, Sp.K.F.R',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Rehab Medik',
    experience: 8,
    rating: 4.87,
    image: '/assets/images/dokter/SPRM/RSYASMIN_SPRM01-dr. Juwita Raudlatul Salsabil, Sp.K.F.R.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Kedokteran Fisik dan Rehabilitasi',
    schedule: { days: ['Rabu', 'Sabtu'], hours: '13:00 - 16:00' },
    bio: 'Kami memahami bahwa proses pemulihan membutuhkan kesabaran dan pendampingan yang tepat. Melalui pelayanan Kedokteran Fisik dan Rehabilitasi, kami membantu memulihkan fungsi tubuh setelah cedera, operasi, stroke, maupun penyakit lainnya agar pasien dapat kembali beraktivitas secara optimal.',
    education: 'Dokter Spesialis Rehabilitasi Medik',
    color: '#b45309'
  },
  {
    id: 'doc-40',
    name: 'dr. Yasmin Bakarman, Sp.KFR',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Rehab Medik',
    experience: 8,
    rating: 4.92,
    image: '/assets/images/dokter/SPRM/RSYASMIN_SPRM02-dr.Yasmin Bakarman, Sp.KFR.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Kedokteran Fisik dan Rehabilitasi',
    schedule: { days: ['Selasa', 'Kamis', 'Jumat'], hours: '15:00 - 18:30' },
    bio: 'Kami percaya setiap kemajuan, sekecil apa pun, merupakan langkah menuju kualitas hidup yang lebih baik. Dengan program rehabilitasi medik yang terencana dan menyeluruh, kami membantu meningkatkan kemampuan fungsional, mengurangi keterbatasan aktivitas, serta mendukung kemandirian pasien dalam menjalani kehidupan sehari-hari.',
    education: 'Dokter Spesialis Rehabilitasi Medik',
    color: '#b45309'
  },
  {
    id: 'doc-41',
    name: 'dr. Noviyanti Eka Wardani, Sp.S',
    specialty: 'Spesialis Medis',
    subSpecialty: 'Saraf',
    experience: 9,
    rating: 4.88,
    image: '/assets/images/dokter/SPSRF/RSYASMIN_SPRF01-dr. Noviyanti Eka Wardani, SpS.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Spesialis Saraf',
    schedule: { days: ['Senin', 'Rabu', 'Kamis'], hours: '09:00 - 13:00' },
    bio: 'Kami memahami bahwa gangguan pada sistem saraf dapat memengaruhi kualitas hidup secara signifikan. Melalui pelayanan Spesialis Saraf yang komprehensif, kami memberikan konsultasi, diagnosis, pengobatan, dan pemantauan berbagai gangguan saraf, seperti stroke, epilepsi, sakit kepala, hingga penyakit neurodegeneratif, dengan mengutamakan keselamatan, kenyamanan, dan kualitas hidup pasien.',
    education: 'Dokter Spesialis Saraf',
    color: '#ca8a04'
  },
  {
    id: 'doc-42',
    name: 'dr. Citra Dwi Novastuti, Sp.T.H.T.K.L',
    specialty: 'Spesialis Medis',
    subSpecialty: 'THT',
    experience: 10,
    rating: 4.86,
    image: '/assets/images/dokter/THT-KL/RSYASMIN_THT-KL01-dr. Citra Dwi Novastuti. Sp. T.H.T.K.L.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Umum',
    schedule: { days: ['Selasa', 'Jumat'], hours: '08:00 - 11:30' },
    bio: 'Kami memahami bahwa kesehatan telinga, hidung, dan tenggorokan berperan penting dalam aktivitas sehari-hari. Melalui pelayanan THT-KL yang menyeluruh, kami membantu menangani berbagai gangguan pendengaran, sinus, suara, serta kelainan kepala dan leher dengan pendekatan yang profesional, nyaman, dan sesuai kebutuhan pasien.',
    education: 'Dokter Spesialis THT-KL',
    color: '#ca8a04'
  },
  {
    id: 'doc-43',
    name: 'dr. Lucky Miftah Saviro, Sp.T.H.T.B.K.L',
    specialty: 'Spesialis Medis',
    subSpecialty: 'THT',
    experience: 8,
    rating: 4.83,
    image: '/assets/images/dokter/THT-KL/RSYASMIN_THT-KL02-dr. Lucky Miftah Saviro. Sp. T.H.T.B.K.L.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'], hours: '07:30 - 14:00' },
    bio: 'Kami hadir untuk membantu mengatasi berbagai keluhan telinga, hidung, tenggorokan, serta kepala dan leher pada anak maupun dewasa. Dengan diagnosis yang tepat, penanganan yang komprehensif, dan komunikasi yang baik, kami berkomitmen memberikan pelayanan yang aman dan nyaman bagi setiap pasien.',
    education: 'Dokter Spesialis THT-KL',
    color: '#ca8a04'
  },
  {
    id: 'doc-44',
    name: 'dr. Ach. Dwipa Perkasa',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 8,
    rating: 4.85,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU01-dr. Ach. Dwipa Perkasa.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 12:00' },
    bio: 'Kami percaya bahwa pencegahan dan deteksi dini merupakan langkah terbaik dalam menjaga kesehatan. Melalui pelayanan dokter umum, kami memberikan konsultasi, pemeriksaan kesehatan, diagnosis awal, pengobatan, serta edukasi kesehatan untuk membantu setiap pasien memperoleh penanganan yang tepat sejak awal.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-45',
    name: 'dr. Ahmat Baihaki',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 7,
    rating: 4.81,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU02-dr. Ahmat Baihaki.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '13:00 - 17:00' },
    bio: 'Kami memberikan pelayanan kesehatan primer secara menyeluruh untuk membantu mengatasi berbagai keluhan medis sehari-hari. Dengan pemeriksaan yang teliti, komunikasi yang baik, serta pendekatan yang profesional, kami mendampingi setiap pasien dalam menjaga kesehatan dirinya dan keluarga.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-46',
    name: 'dr. Azarine Neira Avisha',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 6,
    rating: 4.89,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU03-dr. Azarine Neira Avisha.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Kamis'], hours: '14:00 - 17:30' },
    bio: 'Kami memahami bahwa setiap pasien membutuhkan pelayanan yang ramah, nyaman, dan mudah dipahami. Melalui konsultasi kesehatan, pemeriksaan medis, diagnosis, pengobatan, serta edukasi kesehatan, kami berkomitmen memberikan pelayanan yang berorientasi pada kebutuhan setiap pasien.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-47',
    name: 'dr. Dewangga Sakti Satria Kinasih',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 6,
    rating: 4.86,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU04-dr. Dewangga Sakti Satria Kinasih.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Rabu', 'Jumat'], hours: '15:00 - 19:00' },
    bio: 'Kami mendampingi Anda dan keluarga dalam menjaga kesehatan melalui pelayanan dokter umum yang profesional. Mulai dari konsultasi, diagnosis, tindakan medis dasar, hingga edukasi pencegahan penyakit, kami membantu setiap anggota keluarga memperoleh pelayanan kesehatan yang optimal.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-48',
    name: 'dr. Jasinda Andini Putri Sucipto',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 5,
    rating: 4.93,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU05-dr. Jasinda Andini Putri Sucipto.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Umum',
    schedule: { days: ['Selasa', 'Sabtu'], hours: '09:00 - 12:00' },
    bio: 'Kami percaya bahwa kesehatan yang terjaga memungkinkan Anda terus mendampingi orang-orang tercinta. Melalui pelayanan konsultasi, pemeriksaan medis, pengobatan, dan edukasi pola hidup sehat, kami membantu Anda menjaga kesehatan secara berkelanjutan.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-49',
    name: 'dr. Muhammad Nazmuddin',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 7,
    rating: 4.82,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU06-dr. Muhammad Nazmuddin.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Kamis'], hours: '13:00 - 16:30' },
    bio: 'Kami percaya bahwa komunikasi yang baik merupakan bagian penting dari pelayanan kesehatan. Dengan konsultasi yang terbuka, diagnosis yang tepat, pengobatan yang sesuai, serta penjelasan yang mudah dipahami, kami membantu pasien memahami kondisi kesehatannya dan mengambil keputusan medis dengan lebih percaya diri.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-50',
    name: 'dr. Putri Dwi Fitriani',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 6,
    rating: 4.88,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU07-dr. Putri Dwi Fitriani.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Umum',
    schedule: { days: ['Rabu', 'Jumat'], hours: '10:00 - 13:00' },
    bio: 'Kami berkomitmen membantu Anda menjaga kesehatan melalui pelayanan dokter umum yang profesional dan menyeluruh. Dengan konsultasi, pemeriksaan kesehatan, diagnosis, pengobatan, serta edukasi pencegahan penyakit, kami mendampingi setiap langkah menuju kehidupan yang lebih sehat.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-51',
    name: 'dr. Rika Hardiyanti Hanifa',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 6,
    rating: 4.87,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU08-dr. Rika Hardiyanti Hanifa.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Kamis'], hours: '08:00 - 12:00' },
    bio: 'Kami memahami bahwa setiap pasien memiliki kebutuhan dan kondisi kesehatan yang berbeda. Melalui pelayanan dokter umum yang profesional, kami memberikan konsultasi, pemeriksaan, diagnosis, pengobatan, serta edukasi kesehatan dengan pendekatan yang menyeluruh, komunikatif, dan berorientasi pada kebutuhan setiap pasien.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-52',
    name: 'dr. Sapto Aji Nugroho, MARS',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 9,
    rating: 4.95,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU09-dr. Sapto Aji Nugroho. MARS.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Selasa', 'Jumat'], hours: '09:00 - 13:00' },
    bio: 'Kami berkomitmen memberikan pelayanan kesehatan yang profesional, efektif, dan berorientasi pada kenyamanan pasien. Melalui konsultasi, pemeriksaan, diagnosis, pengobatan, serta edukasi kesehatan yang didukung pengalaman di bidang manajemen rumah sakit, kami berupaya menghadirkan pelayanan yang berkualitas, aman, dan efisien.',
    education: 'Dokter Umum, Magister Administrasi Rumah Sakit',
    color: '#0d9488'
  },
  {
    id: 'doc-53',
    name: 'dr. Wahyu Dian Puspita',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 8,
    rating: 4.8,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU10-dr. Wahyu Dian Puspita.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'], hours: '24 Jam (On-Call)' },
    bio: 'Kami percaya bahwa menjaga kesehatan adalah investasi terbaik untuk masa depan. Melalui pelayanan dokter umum yang menyeluruh, kami memberikan konsultasi, pemeriksaan kesehatan, pengobatan, serta edukasi pola hidup sehat untuk membantu setiap pasien menjalani kehidupan yang lebih sehat dan berkualitas.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-54',
    name: 'dr. Wahyu Irawan, MM',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 9,
    rating: 4.83,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU11-dr. Wahyu Irawan. MM.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'], hours: '08:00 - 15:00' },
    bio: 'Kami menghadirkan pelayanan kesehatan yang memadukan kompetensi medis dan pengalaman di bidang manajemen pelayanan rumah sakit. Dengan konsultasi, pemeriksaan, diagnosis, serta penanganan yang profesional, kami berkomitmen memberikan pelayanan yang cepat, tepat, nyaman, dan berorientasi pada keselamatan pasien.',
    education: 'Dokter Umum, Magister Manajemen',
    color: '#0d9488'
  },
  {
    id: 'doc-55',
    name: 'dr. Sofia Intani Putri',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 5,
    rating: 4.9,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU12-dr.Sofia Intani Putri.png',
    bpjs: true,
    gender: 'Perempuan',
    speciali: 'Dokter Umum',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '08:00 - 14:00' },
    bio: 'Kami percaya bahwa pelayanan kesehatan yang baik dimulai dari komunikasi yang hangat dan saling percaya. Melalui konsultasi, pemeriksaan medis, diagnosis, pengobatan, serta edukasi kesehatan, kami berupaya memberikan pengalaman berobat yang nyaman, ramah, dan sesuai kebutuhan setiap pasien.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-56',
    name: 'dr. Andry Effendy',
    specialty: 'Kesehatan Keluarga',
    subSpecialty: 'Umum',
    experience: 7,
    rating: 4.85,
    image: '/assets/images/dokter/UMUM/RSYASMIN_UMU13-dr. Andry Effendy.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Dokter Umum',
    schedule: { days: ['Selasa', 'Kamis', 'Sabtu'], hours: '09:00 - 13:00' },
    bio: 'Kami memahami bahwa setiap pasien datang dengan harapan untuk kembali sehat. Melalui pelayanan dokter umum yang profesional, pemeriksaan yang menyeluruh, diagnosis yang tepat, serta penanganan yang penuh kepedulian, kami mendampingi setiap pasien menuju proses pemulihan yang optimal.',
    education: 'Dokter Umum',
    color: '#0d9488'
  },
  {
    id: 'doc-57',
    name: 'dr. Yulian Salis Patriawan, Sp.U',
    specialty: 'Bedah & Pemulihan',
    subSpecialty: 'Urologi',
    experience: 8,
    rating: 4.93,
    image: '/assets/images/dokter/UROLOGI/RSYASMIN_URO01-dr. Yulian Salis Patriawan.Sp.U.png',
    bpjs: true,
    gender: 'Laki-laki',
    speciali: 'Spesialis Urologi',
    schedule: { days: ['Senin', 'Rabu', 'Jumat'], hours: '13:00 - 16:00' },
    bio: 'Kami memahami bahwa gangguan saluran kemih dan sistem reproduksi sering kali menimbulkan rasa tidak nyaman bahkan membuat pasien enggan berkonsultasi. Melalui pelayanan urologi yang profesional, kami memberikan konsultasi, diagnosis, serta penanganan berbagai gangguan saluran kemih, prostat, batu saluran kemih, dan sistem reproduksi pria dengan tetap mengutamakan privasi, kenyamanan, dan keselamatan pasien.',
    education: 'Dokter Spesialis Urologi',
    color: '#be123c'
  }
];
